import time
import pygame
import cv2
import sys
from PIL import Image
import matplotlib.pyplot as plt
import matplotlib.image as mpimg

def Alabasta():
    msg = "\n**********Selamat Datang di negeri alabasta**********"
    def a():
        print (msg)
    return a()

def one():
    pygame.mixer.init()
    pygame.mixer.music.load("./Backsound/Luffy Berhasil.mp3")
    pygame.mixer.music.play()
    print("Suatu hari di zaman bajak laut hiduplah seorang anak bernama Monkey D. Luffy")
    time.sleep(3)
    plt.imshow(mpimg.imread("./Pict/Luffy.jpeg"))
    plt.title("Monkey D. Luffy")
    plt.axis('off')
    plt.show()
    print("Luffy beserta temannya pergi berlayar sebagai seorang bajak laut")
    time.sleep(3)
    print("untuk menemukan harta karun 'one piece' dan menjadi raja bajak laut.")
    time.sleep(4)
    plt.imshow(mpimg.imread("./Pict/ThausandSunny.jpg"))
    plt.axis('off')
    plt.show()
    time.sleep(10)
    print("Sampailah mereka di sebuah negeri yang bernama Alabasta")
    Alabasta()
    time.sleep(5)
    plt.imshow(mpimg.imread("./Pict/Alabasta.jpg"))
    plt.title("Kerajaan Alabasta")
    plt.axis('off')
    plt.show()
    time.sleep(5) 
    pygame.mixer.music.stop()
    pygame.mixer.music.load("./Backsound/Luffy Fighting.mp3")
    pygame.mixer.music.play(loops=3)
    print("Kerajaan Alabasta adalah kerajaan gurun yang terletak di Paradise.")
    time.sleep(5)
    print("Kerajaan itu sedang terjadi pemberontakan, dan dalang dibalik itu semua adalah Crocodile.")
    time.sleep(8)
    print("Untuk membebaskan negeri itu luffy pun melawannya.")
    time.sleep(7)
    plt.imshow(mpimg.imread("./Pict/Crocodile.jpeg"))
    plt.title("Musuh : Crocodile")
    plt.axis('off')
    plt.show()

def two():
    pygame.mixer.init()
    pygame.mixer.music.load("./Backsound/Luffy Berhasil.mp3")
    pygame.mixer.music.play()
    time.sleep(5)
    print("Luffy pun dapat membebaskan negeri itu dan melanjutkan perjalanannya untuk mencari one piece.")
    time.sleep(10)
    plt.imshow(mpimg.imread("./Pict/ThausandSunny.jpg"))
    plt.axis('off')
    plt.show()
    time.sleep(3)
    print("Sampailah dia di negeri selanjutnya yaitu Sabaody.")
    time.sleep(6)
    plt.imshow(mpimg.imread("./Pict/Sabaody.jpg"))
    plt.title("Pulau Sabaody")
    plt.axis('off')
    plt.show()
    pygame.mixer.music.load("./Backsound/Luffy Fighting.mp3")
    pygame.mixer.music.play(loops = 20)
    time.sleep(10)
    print("Di pulau itu dia mendapat masalah dari Admiral Kizaru dan Pacifista")
    time.sleep(5)
    print("Sebab ulahnya di negeri Alabasta diduga sebagai dalang pemberontakan oleh angkatan laut.")
    time.sleep(5)
    fig, ax = plt.subplots(ncols=2, nrows=2)
    ax[0, 0].imshow(mpimg.imread("./Pict/Kizaru.jpeg"))
    ax[0, 0].set_title('Admiral Kizaru')
    ax[0, 0].axis('off')
    ax[0, 1].imshow(mpimg.imread("./Pict/Pacifista.jpeg"))
    ax[0, 1].set_title('Pacifista')
    ax[0, 1].axis('off')
    ax[1, 0].axis('off')
    ax[1, 1].axis('off')
    plt.show()
    time.sleep(5)
    print("Melawan Pacifista")
    time.sleep(5)

def two5():
    pygame.mixer.init()
    pygame.mixer.music.load("./Backsound/Kizaru.mp3")
    pygame.mixer.music.play()
    print("Dia pun kalah telak tapi dia tidak menyerah hingga dia dilatih oleh seorang legenda hidup.....")
    time.sleep(5)
    print("salah satu dari kru raja bajak laut sebelumnya yaitu...")
    time.sleep(5)
    print("Rayleigh...")
    plt.imshow(mpimg.imread("./Pict/Rayleigh.jpg"))
    plt.title("Legenda Hidup : Rayleigh")
    plt.axis('off')
    plt.show()
    time.sleep(2)
    print("Luffy-pun belajar kepada Rayleigh selama 2 Tahun.")
    time.sleep(10)
    print("Setelah dia selesai pembelajarannya dan melanjutkan perjalanannya")
    time.sleep(5)
    plt.imshow(mpimg.imread("./Pict/ThausandSunny.jpg"))
    plt.axis('off')
    plt.show()

def three():
    pygame.mixer.init()
    pygame.mixer.music.load("./Backsound/Doflaminggo.mp3")
    pygame.mixer.music.play()
    print("dia kembali berhadapan dengan masalah di pulau dresarosa, dia bertempur melawan Doflaminggo.")
    plt.imshow(mpimg.imread("./Pict/Dofflaminggo.jpeg"))
    plt.title("Legenda Hidup : Rayleigh")
    plt.axis('off')
    time.sleep(6)

def four():
    print("Setelah itu,")
    time.sleep(5)
    print("dia pergi berlayar lagi namun dia di hadapi oleh sebuah pilihan yaitu mau ke wano atau menyelamatkan temannya di Whole Cake Island.")
    time.sleep(5)

def five():
    pygame.mixer.init()
    pygame.mixer.music.load("./Backsound/Big Mom.mp3")
    pygame.mixer.music.play(loops = 2)
    print("Luffy berhasil menyelamatkan temannya.")
    time.sleep(5)
    print("Namun Bigmom sang penguasa Whole Cake Island tidak mau melepaskannya diapun dikejar dan akhirnya terjadilah berhadap-hadapan.")
    time.sleep(10)
    plt.imshow(mpimg.imread("./Pict/bigMom.jpeg"))
    plt.title("Musuh : Big Mom")
    plt.axis('off')
    plt.show()
    time.sleep(2)

def six():
    pygame.mixer.init()
    pygame.mixer.music.load("./Backsound/Luffy Berhasil.mp3")
    pygame.mixer.music.play()
    time.sleep(10)
    print("Akhirnya luffy pun berhasil menyelamatkan temannya dan mereka kembali berlayar menuju wano dan melanjutkan pencariannya menujur one piece.")